version: '3.8'
services:
  db:
    image: postgres:14.1
    container_name: dancing-pony-db
    ports:
     - "${FORWARD_DB_PORT:-54321}:5432"
    volumes:
     - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_NAME}'

volumes:
  postgres:
    name: dancing-pony
networks:
  default:
    name: dancing-pony
