version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: dancing-pony-app
    depends_on:
      - db
      - redis
    networks:
      - default
    volumes:
      - .:/app
    ports:
      - "${HTTP_LISTEN_ADDR:-8080}:${HTTP_LISTEN_ADDR:-8080}"
    env_file:
      - .env
    environment:
      DB_SOURCE: '${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=${DB_SSL_MODE}'
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:14.1
    container_name: dancing-pony-db
    ports:
     - "${FORWARD_DB_PORT:-54321}:5432"
    volumes:
     - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_NAME}'

  redis:
    image: public.ecr.aws/docker/library/redis:7-alpine
    volumes:
      - redis_data:/data:delegated
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - default

volumes:
  postgres:
    driver: local
    name: dancing-pony
  redis_data:
    driver: local
    name: dancing-pony
  
networks:
  default:
    name: dancing-pony
